# Generated by Django 4.0.4 on 2022-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.TimeField(blank=True, default='14:00:37'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, default='14:00:37'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-06-22 14:00:37'),
        ),
    ]
