# Generated by Django 4.0.4 on 2022-06-28 18:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Status', models.CharField(choices=[('on', 'Online'), ('off', 'Uner Mantatince')], default='on', max_length=3)),
                ('Uner_Mantatince_Messge', models.CharField(help_text='Enter field Udermanitain Message', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='batch',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='From_User',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='To_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default='28.06.2022 11:54:41'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default='28.06.2022 11:54:41'),
        ),
        migrations.AlterField(
            model_name='gate_link',
            name='Link_Selected_Item',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 11, 54, 41, 411121)),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 11, 54, 41, 412120)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='From_Ticket',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='USDT_Reciver_Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 11, 54, 41, 412120)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
