# Generated by Django 4.0.4 on 2022-06-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacode',
            name='Data_as_Inserted',
        ),
        migrations.AlterField(
            model_name='areacode',
            name='Country',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='areacode',
            name='Time_Zone',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='areacode',
            name='URL',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.TimeField(blank=True, default='15:20:31'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, default='15:20:31'),
        ),
    ]
