# Generated by Django 4.0.4 on 2022-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_areacode_data_as_inserted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.TimeField(blank=True, default='21:30:54'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, default='21:30:54'),
        ),
    ]
