# Generated by Django 4.0.4 on 2022-05-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_delete_employee_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-title']},
        ),
    ]
