# Generated by Django 4.0.4 on 2022-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_batch_finish_time_alter_batch_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.TimeField(blank=True, default='17:31:11'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, default='17:31:11'),
        ),
        migrations.AlterField(
            model_name='gate_link',
            name='Link_Selected_Item',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-06-22 17:31:11'),
        ),
    ]
