# Generated by Django 4.0.4 on 2022-05-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
