# Generated by Django 4.0.4 on 2022-05-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gate1_alter_news_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate1',
            old_name='about',
            new_name='About_Gate_1',
        ),
        migrations.RenameField(
            model_name='gate1',
            old_name='logo',
            new_name='Gate_1_Logo_tiny',
        ),
        migrations.RenameField(
            model_name='gate1',
            old_name='status',
            new_name='Gate_1_status',
        ),
        migrations.RenameField(
            model_name='gate1',
            old_name='u_ma_me',
            new_name='uner_mantatince_messge',
        ),
    ]
