# Generated by Django 4.0.4 on 2022-06-24 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_batch_finish_time_alter_batch_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.TimeField(blank=True, default='06:29:38'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, default='06:29:38'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-06-24 06:29:38'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 24, 6, 29, 38, 139056)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='From_Ticket',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='USDT_Reciver_Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 24, 6, 29, 38, 139056)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
