# Generated by Django 4.0.4 on 2022-05-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_about_gate1_about_gate_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gate1',
            new_name='Gate1Manage',
        ),
    ]
