# Generated by Django 4.0.4 on 2022-05-28 03:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_gate1_gate1manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate2Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gate_2_status', models.BooleanField(null=True)),
                ('uner_mantatince_messge', models.CharField(help_text='Enter field Udermanitain Message', max_length=100)),
                ('About_Gate_2', ckeditor.fields.RichTextField()),
                ('Gate_2_Logo_tiny', models.ImageField(upload_to='')),
            ],
        ),
    ]
