# Generated by Django 4.0.4 on 2022-05-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='DD',
        ),
        migrations.AddField(
            model_name='format',
            name='DD_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
