# Generated by Django 4.0.4 on 2022-05-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_format_dd_format_dd_int_alter_format_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='DD_int',
            new_name='DD',
        ),
    ]
