# Generated by Django 4.0.4 on 2022-05-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_dd_int_format_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='MM',
            field=models.IntegerField(null=True),
        ),
    ]
