# Generated by Django 4.0.4 on 2022-06-28 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_from_message_to_user_message_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default='28.06.2022 09:44:55'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default='28.06.2022 09:44:55'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 9, 44, 55, 989118)),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 9, 44, 55, 990130)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 9, 44, 55, 990130)),
        ),
    ]
