# Generated by Django 4.0.4 on 2022-05-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_format_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='YY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='disits1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='disits2',
            field=models.IntegerField(null=True),
        ),
    ]
