# Generated by Django 4.0.4 on 2022-06-28 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_batch_finish_time_alter_batch_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link_Name', models.CharField(help_text='Enter Link Name', max_length=100)),
                ('Site_Status', models.CharField(choices=[('on', 'Online'), ('off', 'Uner Mantatince')], default='on', max_length=3)),
                ('Uner_Mantatince_Messge', models.CharField(help_text='Enter field Udermanitain Message', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default='28.06.2022 10:54:17'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default='28.06.2022 10:54:17'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 54, 17, 210224)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 54, 17, 211223)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 54, 17, 211223)),
        ),
    ]
