# Generated by Django 4.0.4 on 2022-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_format_yy_format_disits1_format_disits2'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='string1',
            field=models.CharField(default=0, help_text='Enter field Udermanitain Message', max_length=100),
            preserve_default=False,
        ),
    ]
