# Generated by Django 4.0.4 on 2022-05-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_format_string1'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='batch_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='gate_link_name',
            field=models.CharField(default=0, help_text='Enter field gate_link_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='result1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='result2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='result3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='result4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string10',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string7',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string8',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='string9',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='format',
            name='string1',
            field=models.CharField(help_text='Enter String', max_length=100),
        ),
    ]
