# Generated by Django 4.0.4 on 2022-05-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_format_batch_id_format_gate_link_name_format_result1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate2manage',
            name='Format_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.format'),
        ),
    ]
