# Generated by Django 4.0.4 on 2022-05-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_gate2manage_format_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate1manage',
            name='Format_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.format'),
        ),
    ]
