# Generated by Django 4.0.4 on 2022-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_gate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate_link',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='gate_link',
            name='Link_Logo_large',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gate_link',
            name='Link_Logo_tiny',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gate_link',
            name='Link_Status',
            field=models.CharField(choices=[('At', 'Active'), ('Hd', 'Hidden')], default='At', max_length=2),
        ),
        migrations.AddField(
            model_name='gate_link',
            name='Link_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gate_link',
            name='assin_link_to_gateway',
            field=models.CharField(choices=[('Go', 'Gate 1'), ('Gt', 'Gate 2')], default='Go', max_length=2),
        ),
    ]
