# Generated by Django 4.0.4 on 2022-05-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_gate_link_year_in_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate1manage',
            old_name='About_Gate_1',
            new_name='About_Gate',
        ),
        migrations.RenameField(
            model_name='gate1manage',
            old_name='Gate_1_Logo_tiny',
            new_name='Gate_Logo_tiny',
        ),
        migrations.RenameField(
            model_name='gate1manage',
            old_name='Gate_1_status',
            new_name='Gate_status',
        ),
        migrations.RenameField(
            model_name='gate2manage',
            old_name='About_Gate_2',
            new_name='About_Gate',
        ),
        migrations.RenameField(
            model_name='gate2manage',
            old_name='Gate_2_status',
            new_name='Gate_status',
        ),
        migrations.RenameField(
            model_name='gate2manage',
            old_name='Gate_2_Logo_tiny',
            new_name='Logo_tiny',
        ),
    ]
