# Generated by Django 4.0.4 on 2022-05-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_about_gate_1_gate1manage_about_gate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_link',
            name='assin_link_to_gateway',
            field=models.CharField(choices=[('G1', 'Gate 1'), ('G2', 'Gate 2')], default='G1', max_length=6),
        ),
    ]
