# Generated by Django 4.0.4 on 2022-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_gate_link_assin_link_to_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_link',
            name='Link_Logo_large',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gate_link',
            name='Link_Logo_tiny',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
