# Generated by Django 4.0.4 on 2022-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_gate_link_link_fomart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate2manage',
            name='Format_Item',
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gate_link',
            name='Link_price',
            field=models.FloatField(null=True),
        ),
    ]
