# Generated by Django 4.0.4 on 2022-05-31 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_remove_gate2manage_format_item_alter_balance_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate1manage',
            name='Format_Item',
        ),
        migrations.AlterField(
            model_name='gate1manage',
            name='Gate_status',
            field=models.CharField(choices=[('ol', 'online'), ('um', 'under maintenance')], default='ol', max_length=2),
        ),
        migrations.AlterField(
            model_name='gate2manage',
            name='Gate_status',
            field=models.CharField(choices=[('ol', 'online'), ('um', 'under maintenance')], default='ol', max_length=2),
        ),
        migrations.CreateModel(
            name='TempFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmpStr', models.CharField(max_length=1000000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
