# Generated by Django 4.0.4 on 2022-05-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_gate1manage_format_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='disits1',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='disits2',
        ),
        migrations.AlterField(
            model_name='gate',
            name='DD',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gate',
            name='MM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gate',
            name='YY',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gate',
            name='batch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_link_name',
            field=models.CharField(default='', help_text='Enter field gate_link_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='phone',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='result1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='result2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='result3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='result4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gate',
            name='string9',
            field=models.CharField(default='', max_length=100),
        ),
    ]
