# Generated by Django 4.0.4 on 2022-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_gate_gate_link_name_alter_gate_result1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='result5',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='gate',
            name='status',
            field=models.IntegerField(default=0, help_text='0:In_Queue,1:Processing,2:Fail,3:Success'),
        ),
    ]
