# Generated by Django 4.0.4 on 2022-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_gate_result5_gate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='inserted_text',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
