# Generated by Django 4.0.4 on 2022-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_gate_inserted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, help_text='0:none,1:finished,2:runnig,3:stoped')),
                ('total', models.IntegerField(default=0)),
                ('succeed', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('remains', models.IntegerField(default=0)),
            ],
        ),
    ]
