# Generated by Django 4.0.4 on 2022-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bath_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(default=0, help_text='0:runnig,1:finished,2:stoped'),
        ),
    ]
