# Generated by Django 4.0.4 on 2022-06-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_batch_bath_id_alter_batch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='bath_id',
            new_name='batch_id',
        ),
    ]
