# Generated by Django 4.0.4 on 2022-06-01 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_bath_id_batch_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(default='Running', max_length=100),
        ),
    ]
